version: "3.2"
services:
  ts-consumer-wa-amqplib:
    container_name: ts-consumer-wa-amqplib-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - ts-consumer-wa-amqplib
    env_file:
      - .env
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ${LOTA_WA_RABBITMQ_PATH}/:/var/lib/rabbitmq/
        - ${LOTA_WA_RABBITMQ_PATH}/log/:/var/log/rabbitmq/
    env_file:
      - .env
    networks:
        - ts-consumer-wa-amqplib

networks:
  ts-consumer-wa-amqplib:
    driver: bridge